USER_ID = "U001"
[[DATA_ACLS]]
[DATA_ACLS.DATA_VIEW]
NAME = "json_view"
SOURCE = "json_source"
USER = "json_user"

[DATA_ACLS.VIEW_SCOPE]
[[DATA_ACLS.VIEW_SCOPE.cond]]
where = [ "modified_at > '2023-06-01'" ]